"use client";

import { Camera, CameraOff, Check, Download, ImagePlus, LoaderCircle, RefreshCw, RotateCcw, Share2, ShoppingBag, Sparkles, Trash2, Upload } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { createVirtualTryOn, deleteVirtualTryOnHistory, getMyVirtualTryOnHistory, retryVirtualTryOn, uploadVirtualTryOnPersonImage, type VirtualTryOnJob } from "@/api/virtual-tryon.api";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api";
type Product = { id: string; name?: string; thumbnail?: string; price?: number; brand?: { name?: string } };
type Source = { blob: Blob; url: string; name: string };

export default function VirtualTryOnClient() {
  const productId = useSearchParams().get("productId") || "";
  const videoRef = useRef<HTMLVideoElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const streamRef = useRef<MediaStream | null>(null);
  const [product,setProduct]=useState<Product|null>(null); const [history,setHistory]=useState<VirtualTryOnJob[]>([]); const [source,setSource]=useState<Source|null>(null);
  const [cameraOpen,setCameraOpen]=useState(false); const [facing,setFacing]=useState<"user"|"environment">("user"); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [result,setResult]=useState<VirtualTryOnJob|null>(null);

  useEffect(()=>{ void loadProduct(); void loadHistory(); return stopCamera; },[productId]);
  useEffect(()=>()=>{ if(source?.url.startsWith("blob:")) URL.revokeObjectURL(source.url); },[source]);
  async function loadProduct(){ if(!productId){setProduct(null);return;} try{const response=await fetch(`${API}/products/${productId}`);const data=await response.json();setProduct(data.data||data.product||data);}catch{setMessage("Product could not be loaded.");} }
  async function loadHistory(){ try{const data=await getMyVirtualTryOnHistory();setHistory(data.data||[]);}catch{setHistory([]);} }
  function stopCamera(){streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setCameraOpen(false);}
  async function openCamera(nextFacing=facing){stopCamera();setMessage("");if(!navigator.mediaDevices?.getUserMedia){setMessage("Camera is not supported. Upload a photo instead.");return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:nextFacing},width:{ideal:1280},height:{ideal:1600}},audio:false});streamRef.current=stream;setFacing(nextFacing);setCameraOpen(true);requestAnimationFrame(()=>{if(videoRef.current){videoRef.current.srcObject=stream;void videoRef.current.play();}});}catch{setMessage("Camera permission was denied. You can upload a photo instead.");}}
  function capture(){const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas||!video.videoWidth){setMessage("Camera is still starting.");return;}canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d")?.drawImage(video,0,0);canvas.toBlob(blob=>{if(!blob)return;setSource({blob,url:URL.createObjectURL(blob),name:"camera-capture.jpg"});stopCamera();setMessage("Photo captured. Review it, then run try-on.");},"image/jpeg",.9);}
  function chooseFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>8*1024*1024){setMessage("Choose a JPEG, PNG, or WebP image under 8MB.");return;}setSource({blob:file,url:URL.createObjectURL(file),name:file.name});stopCamera();setMessage("Photo selected. Review it, then run try-on.");}
  async function run(){if(!productId){setMessage("Open Virtual Try-On from a product page first.");return;}if(!source){setMessage("Capture or upload a full-body photo first.");return;}setBusy(true);setMessage("Uploading your photo securely...");try{const uploaded=await uploadVirtualTryOnPersonImage(source.blob,source.name);setMessage("AI is creating your try-on...");const response=await createVirtualTryOn({productId,personImage:uploaded.url});setResult(response.data);await loadHistory();setMessage(response.data?.status==="COMPLETED"?"Your try-on is ready.":response.data?.error||"Try-on could not be completed.");}catch(error){setMessage(error instanceof Error?error.message:"Virtual Try-On failed");}finally{setBusy(false);}}
  async function share(){const url=result?.resultImage;if(!url)return;if(navigator.share)await navigator.share({title:"My Virtual Try-On",url});else{await navigator.clipboard.writeText(url);setMessage("Result link copied.");}}
  async function addToCart(){if(!productId)return;const response=await fetch(`${API}/cart`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId,quantity:1})});setMessage(response.ok?"Added to cart.":"Please sign in to add this item.");}
  async function retry(id:string){setBusy(true);try{const response=await retryVirtualTryOn(id);setResult(response.data);await loadHistory();}finally{setBusy(false);}}
  async function remove(id:string){await deleteVirtualTryOnHistory(id);await loadHistory();if(result?.id===id)setResult(null);}

  return <main className="min-h-screen bg-[hsl(var(--background))] px-4 py-8 text-[hsl(var(--foreground))] md:px-8">
    <div className="mx-auto max-w-6xl"><header className="flex flex-col gap-4 border-b border-[hsl(var(--border))] pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase text-[hsl(var(--primary))]">AI fitting room</p><h1 className="mt-2 text-3xl font-black">Virtual Try-On</h1><p className="mt-2 max-w-2xl text-sm text-[hsl(var(--muted-foreground))]">Use your live camera or upload a clear, well-lit full-body photo. Your image is used only to create and save your try-on history.</p></div><span className="inline-flex items-center gap-2 text-sm"><Sparkles size={16}/> FASHN AI</span></header>
    <section className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(280px,.65fr)]"><div className="overflow-hidden rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))]"><div className="relative aspect-[4/5] max-h-[680px] bg-black">
      {cameraOpen?<video ref={videoRef} autoPlay playsInline muted className="h-full w-full object-cover"/>:source?<img src={source.url} alt="Try-on person preview" className="h-full w-full object-contain"/>:<div className="grid h-full place-items-center p-8 text-center text-white/70"><div><Camera size={42} className="mx-auto"/><p className="mt-3 font-semibold">Start camera or upload a full-body photo</p></div></div>}<canvas ref={canvasRef} className="hidden"/>
      {cameraOpen?<div className="absolute inset-x-0 bottom-4 flex justify-center gap-3"><button onClick={capture} className="grid h-14 w-14 place-items-center rounded-full bg-white text-black" title="Capture photo"><Camera size={22}/></button><button onClick={()=>openCamera(facing==="user"?"environment":"user")} className="grid h-14 w-14 place-items-center rounded-full bg-black/70 text-white" title="Switch camera"><RefreshCw size={20}/></button><button onClick={stopCamera} className="grid h-14 w-14 place-items-center rounded-full bg-black/70 text-white" title="Stop camera"><CameraOff size={20}/></button></div>:null}
    </div><div className="grid gap-3 p-4 sm:grid-cols-3"><button onClick={()=>openCamera()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-[hsl(var(--primary))] px-4 font-bold text-[hsl(var(--primary-foreground))]"><Camera size={18}/> Camera</button><label className="inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-md border border-[hsl(var(--border))] px-4 font-bold"><Upload size={18}/> Upload<input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile} className="sr-only"/></label><button onClick={run} disabled={busy||!source||!productId} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-emerald-600 px-4 font-bold text-white disabled:opacity-50">{busy?<LoaderCircle size={18} className="animate-spin"/>:<Sparkles size={18}/>} Try On</button></div></div>
    <aside className="space-y-5"><section className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4"><h2 className="font-bold">Selected product</h2>{product?<div className="mt-4 flex gap-3">{product.thumbnail?<img src={product.thumbnail} alt={product.name||"Product"} className="h-24 w-20 rounded-md object-cover"/>:<div className="grid h-24 w-20 place-items-center bg-[hsl(var(--muted))]"><ImagePlus/></div>}<div><b>{product.name}</b><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{product.brand?.name}</p>{product.price?<p className="mt-2 font-bold">Tk {product.price.toLocaleString()}</p>:null}</div></div>:<p className="mt-3 text-sm text-[hsl(var(--muted-foreground))]">Select a product before starting.</p>}</section>
    {result?.resultImage?<section className="rounded-lg border border-emerald-500/40 bg-[hsl(var(--card))] p-4"><div className="flex items-center gap-2 font-bold text-emerald-500"><Check size={18}/> Result ready</div><img src={result.resultImage} alt="Virtual try-on result" className="mt-3 aspect-[4/5] w-full rounded-md object-contain"/><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={share} className="inline-flex items-center justify-center gap-2 rounded-md border p-2"><Share2 size={16}/> Share</button><a href={result.resultImage} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-md border p-2"><Download size={16}/> Open</a><button onClick={addToCart} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-md bg-[hsl(var(--primary))] p-3 font-bold text-[hsl(var(--primary-foreground))]"><ShoppingBag size={17}/> Add to cart</button></div></section>:null}
    {message?<p role="status" className="rounded-md border border-[hsl(var(--border))] bg-[hsl(var(--muted))] p-3 text-sm">{message}</p>:null}</aside></section>
    <section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Try-On History</h2><button onClick={loadHistory} title="Refresh history" className="grid h-11 w-11 place-items-center rounded-md border"><RefreshCw size={17}/></button></div>{history.length?<div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{history.map(item=><article key={item.id} className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-3"><img src={item.resultImage||item.personImage} alt={item.product?.name||"Try-on"} className="aspect-[4/5] w-full rounded-md object-cover"/><div className="mt-3 flex items-start justify-between gap-2"><div><b>{item.product?.name||"Try-On"}</b><p className="text-xs text-[hsl(var(--muted-foreground))]">{item.status}</p></div><div className="flex"><button onClick={()=>retry(item.id)} title="Retry"><RotateCcw size={17}/></button><button onClick={()=>remove(item.id)} title="Delete" className="ml-3 text-red-500"><Trash2 size={17}/></button></div></div></article>)}</div>:<p className="mt-4 rounded-md border border-dashed p-6 text-center text-sm text-[hsl(var(--muted-foreground))]">No try-on history yet.</p>}</section></div>
  </main>;
}

