"use client";
import{useRef,useState,useEffect}from"react";import styles from "./page.module.css";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:5000/api";type M={role:"user"|"assistant";content:string};
function token(){return localStorage.getItem("token")??localStorage.getItem("accessToken")??localStorage.getItem("authToken")}
async function api(path:string,init?:RequestInit){const r=await fetch(`${API}/ai/business-intelligence${path}`,{...init,headers:{"Content-Type":"application/json",...(token()?{Authorization:`Bearer ${token()}`}:{})}});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||j?.error?.code||"Request failed");return j.data}
export default function Page(){const[tab,setTab]=useState("Advisor");const[input,setInput]=useState("");const[busy,setBusy]=useState(false);const[msgs,setMsgs]=useState<M[]>([{role:"assistant",content:"Business AI Advisor is connected to your tenant and store data. Ask about sales, products, customers, inventory, campaigns, targets, or budgets."}]);const[data,setData]=useState<any>();const[snapshot,setSnapshot]=useState<any>();const end=useRef<HTMLDivElement>(null);
useEffect(()=>{api("/snapshot").then(setSnapshot).catch(()=>null)},[]);useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[msgs]);
async function send(){const text=input.trim();if(!text||busy)return;setMsgs(x=>[...x,{role:"user",content:text}]);setInput("");setBusy(true);try{const d=await api("/chat",{method:"POST",body:JSON.stringify({message:text})});setData(d);setMsgs(x=>[...x,{role:"assistant",content:d.directAnswer||d.headline}])}catch(e:any){setMsgs(x=>[...x,{role:"assistant",content:`Error: ${e.message}`}])}finally{setBusy(false)}}
function voice(){const C=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!C)return alert("Speech recognition unavailable.");const r=new C();r.lang="bn-BD";r.onresult=(e:any)=>setInput(e.results[0][0].transcript);r.start()}
async function runTool(){const path=tab==="Forecast"?"/forecast":tab==="Executives"?"/executive-advisors":tab==="Reports"?"/reports/executive":`/intelligence/${tab.toLowerCase()}`;const d=await api(path,tab==="Reports"?{method:"POST",body:JSON.stringify({days:30})}:undefined);setData(d)}
const tabs=["Advisor","Multi-Agent","Deep Reasoning","Sales","Finance","Inventory","Customers","Forecast","Scenario","Goal Planner","Memory","Executives","Predictive","Reports","Decisions","Actions"];
return <main className={styles.shell}><section className={styles.hero}><div><div className={styles.eyebrow}>TENANT BUSINESS INTELLIGENCE</div><h1 className={styles.title}>SAQSO Business AI Advisor</h1><p className={styles.sub}>Evidence-backed advice using authenticated tenant/store data, live provider reasoning, approval actions and printable plans.</p></div><div className={styles.chips}><span className={styles.chip}>Tenant Scoped</span><span className={styles.chip}>Provider Live</span><span className={styles.chip}>Voice Ready</span></div></section><section className={styles.layout}><aside className={`${styles.panel} ${styles.nav}`}>{tabs.map(x=><button key={x} data-active={tab===x} onClick={()=>setTab(x)}>{x}</button>)}</aside><section className={`${styles.panel} ${styles.chat}`}><div className={styles.messages}>{msgs.map((m,i)=><div key={i} className={`${styles.msg} ${m.role==="user"?styles.user:styles.assistant}`}>{m.content}</div>)}<div ref={end}/></div><div className={styles.composer}>{tab!=="Advisor"&&<button onClick={runTool}>Run {tab}</button>}<textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Example: Amar sale kom keno? 20,000 pcs target er jonno 5 lakh budget plan dao."/><div className={styles.actions}><button onClick={send} disabled={busy}>{busy?"Analyzing...":"Ask Advisor"}</button><button onClick={voice}>Voice</button><button onClick={()=>window.print()}>Print</button></div></div></section><aside className={`${styles.panel} ${styles.evidence}`}><h3>Live Snapshot</h3><div className={styles.cards}>{Object.entries(snapshot?.kpis||{}).slice(0,8).map(([k,v])=><div key={k} className={styles.card}><small>{k}</small><b>{String(v)}</b></div>)}</div><h3>Evidence & Plan</h3><pre>{data?JSON.stringify(data,null,2):"Ask a question or run an intelligence tool."}</pre></aside></section></main>}