"use client";
import { useCallback, useEffect, useState } from "react";
import { BookOpenCheck, BrainCircuit, FileKey2, Settings2 } from "lucide-react";
import { getAiPlatformRegistry, saveAiEnterpriseSetting, saveAiModel, saveAiPolicy, saveAiPrompt } from "@/services/ai-control.api";
import styles from "./AiPlatformRegistry.module.css";

type Registry = { prompts:any[]; models:any[]; policies:any[]; settings:any[]; governance:{schemaVersion:string} };
const empty:Registry={prompts:[],models:[],policies:[],settings:[],governance:{schemaVersion:"AI-G1"}};

export default function AiPlatformRegistry(){
 const[tab,setTab]=useState("prompts"),[data,setData]=useState<Registry>(empty),[status,setStatus]=useState("Loading enterprise registries..."),[busy,setBusy]=useState(false);
 const[prompt,setPrompt]=useState({key:"",version:1,category:"core",title:"",template:"",approved:false});
 const[model,setModel]=useState({key:"",providerKey:"openai",modelId:"",modelType:"chat",displayName:"",enabled:false,priority:100});
 const[doc,setDoc]=useState({key:"",title:"",description:"",json:"{}",enabled:true});
 const load=useCallback(async()=>{try{setData(await getAiPlatformRegistry());setStatus("Platform registries synchronized.")}catch(e){setStatus(e instanceof Error?e.message:"Run AI-G1 database preflight first.")}},[]);
 useEffect(()=>{void load()},[load]);
 async function savePrompt(){setBusy(true);try{await saveAiPrompt({...prompt,variables:[...prompt.template.matchAll(/\{\{\s*([\w.-]+)\s*\}\}/g)].map(x=>x[1])});setPrompt({key:"",version:1,category:"core",title:"",template:"",approved:false});await load()}catch(e){setStatus(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}}
 async function saveModel(){setBusy(true);try{await saveAiModel({...model,displayName:model.displayName||model.modelId,config:{}});setModel({key:"",providerKey:"openai",modelId:"",modelType:"chat",displayName:"",enabled:false,priority:100});await load()}catch(e){setStatus(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}}
 async function saveDocument(){setBusy(true);try{const value=JSON.parse(doc.json);if(tab==="policies")await saveAiPolicy(doc.key,{title:doc.title,description:doc.description,enabled:doc.enabled,policy:value});else await saveAiEnterpriseSetting(doc.key,{label:doc.title,description:doc.description,value});setDoc({key:"",title:"",description:"",json:"{}",enabled:true});await load()}catch(e){setStatus(e instanceof Error?e.message:"Invalid JSON or save failed")}finally{setBusy(false)}}
 const rows=tab==="prompts"?data.prompts:tab==="models"?data.models:tab==="policies"?data.policies:data.settings;
 return <section className={styles.shell}><div className={styles.head}><div><span>AI-G1 · {data.governance?.schemaVersion}</span><h2>Enterprise AI platform registry</h2><p>Versioned prompts, governed models, platform policies and enterprise settings. SUPER_ADMIN only.</p></div><b>{rows.length} records</b></div>
 <nav className={styles.tabs}><button className={tab==="prompts"?styles.active:""} onClick={()=>setTab("prompts")}><BookOpenCheck size={16}/>Prompt Manager</button><button className={tab==="models"?styles.active:""} onClick={()=>setTab("models")}><BrainCircuit size={16}/>Model Manager</button><button className={tab==="policies"?styles.active:""} onClick={()=>setTab("policies")}><FileKey2 size={16}/>AI Policies</button><button className={tab==="settings"?styles.active:""} onClick={()=>setTab("settings")}><Settings2 size={16}/>Enterprise Settings</button></nav><div className={styles.status}>{status}</div>
 <div className={styles.body}><div className={styles.records}>{rows.map(r=><article key={`${r.key}-${r.version??"current"}`}><div><b>{r.title||r.displayName||r.label||r.key}</b><code>{r.key}{r.version?` · v${r.version}`:""}</code></div><span className={r.approved||r.enabled?styles.enabled:styles.disabled}>{r.approved?"Approved":r.enabled?"Enabled":"Controlled"}</span><small>{r.category||r.providerKey||r.description||"Platform configuration"}</small></article>)}{!rows.length&&<p className={styles.empty}>No records yet. Create the first governed record.</p>}</div>
 <div className={styles.editor}>{tab==="prompts"&&<><h3>Create or update prompt version</h3><label>Registry key<input value={prompt.key} onChange={e=>setPrompt({...prompt,key:e.target.value})}/></label><div className={styles.two}><label>Version<input type="number" min="1" value={prompt.version} onChange={e=>setPrompt({...prompt,version:Number(e.target.value)})}/></label><label>Category<input value={prompt.category} onChange={e=>setPrompt({...prompt,category:e.target.value})}/></label></div><label>Title<input value={prompt.title} onChange={e=>setPrompt({...prompt,title:e.target.value})}/></label><label>Template<textarea rows={6} value={prompt.template} onChange={e=>setPrompt({...prompt,template:e.target.value})}/></label><label className={styles.check}><input type="checkbox" checked={prompt.approved} onChange={e=>setPrompt({...prompt,approved:e.target.checked})}/>Approved for runtime</label><button disabled={busy||!prompt.key||!prompt.title||!prompt.template} onClick={savePrompt}>Save prompt version</button></>}
 {tab==="models"&&<><h3>Register governed model</h3><label>Registry key<input value={model.key} onChange={e=>setModel({...model,key:e.target.value})}/></label><div className={styles.two}><label>Provider<input value={model.providerKey} onChange={e=>setModel({...model,providerKey:e.target.value})}/></label><label>Model type<select value={model.modelType} onChange={e=>setModel({...model,modelType:e.target.value})}><option>chat</option><option>vision</option><option>image</option><option>embedding</option><option>speech</option><option>video</option></select></label></div><label>Provider model ID<input value={model.modelId} onChange={e=>setModel({...model,modelId:e.target.value})}/></label><label>Display name<input value={model.displayName} onChange={e=>setModel({...model,displayName:e.target.value})}/></label><label className={styles.check}><input type="checkbox" checked={model.enabled} onChange={e=>setModel({...model,enabled:e.target.checked})}/>Enabled after provider readiness review</label><button disabled={busy||!model.key||!model.modelId} onClick={saveModel}>Save model</button></>}
 {(tab==="policies"||tab==="settings")&&<><h3>{tab==="policies"?"Create AI policy":"Create enterprise setting"}</h3><label>Key<input value={doc.key} onChange={e=>setDoc({...doc,key:e.target.value})}/></label><label>Title<input value={doc.title} onChange={e=>setDoc({...doc,title:e.target.value})}/></label><label>Description<input value={doc.description} onChange={e=>setDoc({...doc,description:e.target.value})}/></label><label>JSON value<textarea rows={7} value={doc.json} onChange={e=>setDoc({...doc,json:e.target.value})}/></label>{tab==="policies"&&<label className={styles.check}><input type="checkbox" checked={doc.enabled} onChange={e=>setDoc({...doc,enabled:e.target.checked})}/>Policy enabled</label>}<button disabled={busy||!doc.key||!doc.title} onClick={saveDocument}>Save {tab==="policies"?"policy":"setting"}</button></>}</div></div></section>
}
