export type PluginManifest = {
  schemaVersion: "1.0";
  pluginKey: string; name: string; description: string;
  vendor: { key: string; name: string; website?: string };
  version: string; minimumPlatformVersion: string; maximumPlatformVersion: string;
  dependencies: Array<{ pluginKey: string; versionRange: string; optional: boolean; mustBeActive: boolean }>;
  conflicts: Array<{ type: string; key: string; reason: string }>;
  supportedRoles: string[]; tenantScope: "PLATFORM_ONLY"|"TENANT_ASSIGNABLE"|"ALL_TENANTS";
  subscriptionRequirements: { requiredPlanKeys: string[]; requiredEntitlements: string[] };
  featureFlags: string[];
  files: Array<{ owner:"server"|"admin"|"client"; sourcePath:string; destinationPath:string; sha256:string; sizeBytes:number; contentType:string; operation:"create"|"replace" }>;
  databaseChanges: { hasChanges:boolean; migrationPlanPath:string|null; rollbackPlanPath:string|null; destructive:false };
  permissions:string[]; menus:string[]; widgets:string[]; settings:string[]; events:string[];
  healthChecks:Array<{key:string;type:string;required:boolean;target?:string}>;
  installStrategy:{mode:"DECLARATIVE_TRANSACTION";requiresRestart:boolean;requiresRebuild:boolean};
  rollbackStrategy:{mode:"DECLARATIVE_TRANSACTION";requiresRestart:boolean;requiresRebuild:boolean};
  uninstallStrategy:{preserveData:true;removeOwnedFiles:boolean;removeRegistrations:boolean};
};
export type ArchiveEntry={path:string;compressedSize:number;uncompressedSize:number;externalAttributes:number};
export type ValidationIssue={code:string;path?:string;message:string};
export type InstallationPlan={pluginKey:string;version:string;packageSha256:string;files:PluginManifest["files"];dependencies:PluginManifest["dependencies"];conflicts:PluginManifest["conflicts"];databaseChanges:PluginManifest["databaseChanges"];requiresRestart:boolean;requiresRebuild:boolean;fingerprint:string};
