import {randomUUID} from "crypto";
import {Router} from "express";
import prisma from "../../config/prisma";
import {protect,type AuthRequest} from "../auth/auth.middleware";
const router=Router();const BUILT_INS=[{"registryKey":"fashion","slug":"fashion","name":"Fashion","codePath":"client/src/templates/fashion"},{"registryKey":"luxury","slug":"luxury","name":"Luxury","codePath":"client/src/templates/luxury"},{"registryKey":"modern","slug":"modern","name":"Modern","codePath":"client/src/templates/modern"},{"registryKey":"saqsobuild","slug":"saqsobuild","name":"SaqsoBuild","codePath":"client/src/templates/saqsobuild"}] as const;
const clean=(v:unknown)=>String(v||"").trim();const param=(v:string|string[])=>Array.isArray(v)?v[0]||"":clean(v);
function superAdmin(req:AuthRequest,res:any,next:any){if(String(req.user?.role||"").toUpperCase()!=="SUPER_ADMIN")return res.status(403).json({success:false,message:"Super Admin required"});next()}
async function event(req:AuthRequest,action:string,status:string,metadata:any){await prisma.$executeRawUnsafe(`INSERT INTO template_lifecycle_events(id,action,status,actor_id,metadata) VALUES($1,$2,$3,$4,$5::jsonb)`,randomUUID(),action,status,req.user?.id||null,JSON.stringify(metadata||{}))}
router.get("/registry",protect,superAdmin,async(_q,res)=>{const [templates,registry,stores]=await Promise.all([prisma.template.findMany({orderBy:{name:"asc"},include:{stores:true}}),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM template_registry_entries ORDER BY name ASC`),prisma.store.findMany({orderBy:{name:"asc"},include:{tenant:true,templates:{include:{template:true}},domains:true}})]);res.json({success:true,data:{templates,registry,stores,builtIns:BUILT_INS}})});
router.post("/sync",protect,superAdmin,async(req,res)=>{for(const i of BUILT_INS){const t=await prisma.template.upsert({where:{slug:i.slug},create:{name:i.name,slug:i.slug,description:`${i.name} built-in template`,isActive:true},update:{name:i.name,isActive:true}});await prisma.$executeRawUnsafe(`INSERT INTO template_registry_entries(id,template_id,slug,registry_key,name,source_type,version,vendor,engine,code_path,manifest,health,status,last_synced_at,updated_at) VALUES($1,$2,$3,$4,$5,'BUILT_IN','1.0.0','saqso.platform','NEXT_APP_ROUTER',$6,$7::jsonb,'DISCOVERED','REGISTERED',NOW(),NOW()) ON CONFLICT(slug) DO UPDATE SET template_id=EXCLUDED.template_id,registry_key=EXCLUDED.registry_key,name=EXCLUDED.name,code_path=EXCLUDED.code_path,manifest=EXCLUDED.manifest,last_synced_at=NOW(),updated_at=NOW()`,randomUUID(),t.id,i.slug,i.registryKey,i.name,i.codePath,JSON.stringify(i))}const all=await prisma.template.findMany();for(const t of all){if(BUILT_INS.some(i=>i.slug===t.slug))continue;await prisma.$executeRawUnsafe(`INSERT INTO template_registry_entries(id,template_id,slug,registry_key,name,source_type,version,vendor,engine,manifest,health,status,last_synced_at,updated_at) VALUES($1,$2,$3,$4,$5,'IMPORTED','1.0.0','migration-studio','NEXT_APP_ROUTER',$6::jsonb,'DISCOVERED','REGISTERED',NOW(),NOW()) ON CONFLICT(slug) DO UPDATE SET template_id=EXCLUDED.template_id,name=EXCLUDED.name,source_type='IMPORTED',last_synced_at=NOW(),updated_at=NOW()`,randomUUID(),t.id,t.slug,t.slug,t.name,JSON.stringify({slug:t.slug,name:t.name}))}await event(req,"REGISTRY_SYNC","PASS",{count:all.length});res.json({success:true,data:{builtIns:BUILT_INS.length,total:all.length}})});
router.post("/health/:slug",protect,superAdmin,async(req,res)=>{const slug=param(req.params.slug);const t=await prisma.template.findUnique({where:{slug}});const r=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM template_registry_entries WHERE slug=$1 LIMIT 1`,slug);const checks={databaseTemplate:Boolean(t),registryEntry:Boolean(r[0]),codePath:Boolean(r[0]?.code_path),catalogActive:Boolean(t?.isActive)};const score=Math.round(Object.values(checks).filter(Boolean).length/Object.keys(checks).length*100);const health=score===100?"HEALTHY":score>=50?"WARNING":"BROKEN";await prisma.$executeRawUnsafe(`UPDATE template_registry_entries SET health=$1,last_health_at=NOW(),updated_at=NOW() WHERE slug=$2`,health,slug);await event(req,"HEALTH_CHECK",health,{slug,score,checks});res.json({success:true,data:{slug,health,score,checks}})});
router.get("/events",protect,superAdmin,async(_q,res)=>res.json({success:true,data:await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM template_lifecycle_events ORDER BY created_at DESC LIMIT 200`)}));

router.post("/activate/:id",protect,superAdmin,async(req,res)=>{const id=param(req.params.id);const target=await prisma.storeTemplate.findUnique({where:{id},include:{template:true,store:true}});if(!target)return res.status(404).json({success:false,message:"Assignment not found"});const h=await prisma.$queryRawUnsafe<any[]>(`SELECT health FROM template_registry_entries WHERE slug=$1 LIMIT 1`,target.template.slug);if(h[0]?.health!=="HEALTHY")return res.status(409).json({success:false,message:"Health PASS required"});const prev=await prisma.storeTemplate.findFirst({where:{storeId:target.storeId,isActive:true},include:{template:true}});const sid=randomUUID();await prisma.$transaction(async tx=>{await tx.storeTemplate.updateMany({where:{storeId:target.storeId},data:{isActive:false}});await tx.storeTemplate.update({where:{id},data:{isActive:true}});await tx.storeSetting.updateMany({where:{singletonKey:`store:${target.storeId}`},data:{activeTemplate:target.template.slug}})});await prisma.$executeRawUnsafe(`INSERT INTO template_activation_snapshots(id,store_id,previous_assignment_id,next_assignment_id,previous_template_slug,next_template_slug,status) VALUES($1,$2,$3,$4,$5,$6,'READY')`,sid,target.storeId,prev?.id||null,id,prev?.template?.slug||null,target.template.slug);await event(req,"ACTIVATE","PASS",{storeId:target.storeId,slug:target.template.slug,snapshotId:sid});res.json({success:true,data:{activeTemplate:target.template.slug,previousTemplate:prev?.template?.slug||null,snapshotId:sid}})});
router.post("/rollback/:storeId",protect,superAdmin,async(req,res)=>{const storeId=param(req.params.storeId);const s=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM template_activation_snapshots WHERE store_id=$1 AND status='READY' ORDER BY created_at DESC LIMIT 1`,storeId);const snap=s[0];if(!snap?.previous_assignment_id)return res.status(404).json({success:false,message:"No rollback snapshot"});const prev=await prisma.storeTemplate.findUnique({where:{id:snap.previous_assignment_id},include:{template:true}});if(!prev)return res.status(409).json({success:false,message:"Previous assignment missing"});await prisma.$transaction(async tx=>{await tx.storeTemplate.updateMany({where:{storeId},data:{isActive:false}});await tx.storeTemplate.update({where:{id:prev.id},data:{isActive:true}});await tx.storeSetting.updateMany({where:{singletonKey:`store:${storeId}`},data:{activeTemplate:prev.template.slug}})});await prisma.$executeRawUnsafe(`UPDATE template_activation_snapshots SET status='RESTORED',restored_at=NOW() WHERE id=$1`,snap.id);await event(req,"ROLLBACK","PASS",{storeId,slug:prev.template.slug});res.json({success:true,data:{activeTemplate:prev.template.slug}})});

export default router;
