"use client";
import {useEffect,useRef,useState} from "react";
import styles from "./page.module.css";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:5000/api";
type Message={role:"user"|"assistant";content:string};
function token(){return localStorage.getItem("token")??localStorage.getItem("accessToken")??localStorage.getItem("authToken")}
async function api(path:string,init?:RequestInit){const r=await fetch(`${API}/ai-development-copilot${path}`,{...init,headers:{"Content-Type":"application/json",...(token()?{Authorization:`Bearer ${token()}`}:{})}});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"Request failed");return j.data}
export default function Page(){
 const[tab,setTab]=useState("Chat");const[input,setInput]=useState("");const[busy,setBusy]=useState(false);const[messages,setMessages]=useState<Message[]>([{role:"assistant",content:"SAQSO AI Developer is ready. Ask in বাংলা, English, or Banglish about architecture, bugs, code, plugins, testing, or deployment."}]);const[providers,setProviders]=useState<any[]>([]);const[result,setResult]=useState<any>();const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{api("/providers").then(setProviders).catch(()=>setProviders([]))},[]);useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[messages]);
 async function send(){const prompt=input.trim();if(!prompt||busy)return;setMessages(x=>[...x,{role:"user",content:prompt}]);setInput("");setBusy(true);try{const d=await api("/live-chat",{method:"POST",body:JSON.stringify({prompt})});setMessages(x=>[...x,{role:"assistant",content:d.answer||"No response"}]);setResult(d)}catch(e:any){setMessages(x=>[...x,{role:"assistant",content:`Error: ${e.message}`}])}finally{setBusy(false)}}
 function voice(){const C=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!C)return alert("Speech recognition is not supported in this browser.");const r=new C();r.lang="bn-BD";r.interimResults=false;r.onresult=(e:any)=>setInput((v)=>`${v} ${e.results[0][0].transcript}`.trim());r.start()}
 const tools=["Chat","Repository","Architecture","Review","Debug","Refactor","Docs","Patch / Diff","Tests","Plugin Composer","Deployment"];
 return <main className={styles.shell}><section className={styles.hero}><div><div className={styles.eyebrow}>SAQSO.AI / PLATFORM DEVELOPMENT</div><h1 className={styles.title}>AI Developer Command Workspace</h1><p className={styles.sub}>Live provider-backed conversation, repository intelligence, approval-governed artifacts, debugging and deployment assistance.</p></div><div className={styles.status}><span className={styles.badge}>Provider Live</span><span className={styles.badge}>No Auto-Mutation</span><span className={styles.badge}>বাংলা + English</span></div></section><section className={styles.grid}><aside className={`${styles.panel} ${styles.nav}`}>{tools.map(x=><button key={x} data-active={tab===x} onClick={()=>setTab(x)}>{x}</button>)}</aside><section className={`${styles.panel} ${styles.chat}`}><div className={styles.messages}>{messages.map((m,i)=><div key={i} className={`${styles.msg} ${m.role==="user"?styles.user:styles.assistant}`}>{m.content}</div>)}<div ref={end}/></div><div className={styles.composer}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`Ask ${tab.toLowerCase()} question...`}/><div className={styles.actions}><button onClick={send} disabled={busy}>{busy?"Thinking...":"Send"}</button><button onClick={voice}>Voice</button></div></div></section><aside className={`${styles.panel} ${styles.aside}`}><h3>Provider Status</h3>{providers.map(p=><div className={styles.provider} key={p.name}><b>{p.displayName}</b><div className={p.enabled?styles.on:styles.off}>{p.enabled?"Enabled":"Not configured"}</div><small>{p.defaultChatModel||"—"}</small></div>)}<h3>Last Execution</h3><pre>{result?JSON.stringify(result,null,2):"No execution yet."}</pre></aside></section></main>
}