import { createHash } from "crypto";
import path from "path";
import type { ArchiveEntry, PluginManifest, ValidationIssue } from "./plugin-platform.types";
const KEY=/^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)+$/; const SEMVER=/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;
export const sha256=(value:Buffer|string)=>createHash("sha256").update(value).digest("hex");
export function safeRelativePath(value:string){if(!value||value.includes("\\")||value.includes(":")||value.startsWith("/")||value.includes("\0"))return false;const n=path.posix.normalize(value);return n===value&&!n.startsWith("../")&&!n.includes("/../")&&!n.endsWith("/..");}
export function validateManifest(input:unknown):{manifest?:PluginManifest;issues:ValidationIssue[]}{const issues:ValidationIssue[]=[];if(!input||typeof input!=="object"||Array.isArray(input))return{issues:[{code:"PKG_MANIFEST_TYPE",message:"Manifest must be an object"}]};const m=input as PluginManifest;if(m.schemaVersion!=="1.0")issues.push({code:"PKG_MANIFEST_SCHEMA",message:"Unsupported schemaVersion"});if(!KEY.test(String(m.pluginKey||"")))issues.push({code:"PKG_MANIFEST_KEY",message:"Invalid pluginKey"});for(const [k,v] of [["version",m.version],["minimumPlatformVersion",m.minimumPlatformVersion],["maximumPlatformVersion",m.maximumPlatformVersion]] as const)if(!SEMVER.test(String(v||"")))issues.push({code:"PKG_MANIFEST_SEMVER",path:k,message:`Invalid ${k}`});if(!Array.isArray(m.files))issues.push({code:"PKG_MANIFEST_FILES",message:"files must be an array"});else{const destinations=new Set<string>();for(const f of m.files){if(!["server","admin","client"].includes(f.owner)||!safeRelativePath(f.sourcePath)||!safeRelativePath(f.destinationPath))issues.push({code:"PKG_MANIFEST_PATH",path:f.destinationPath,message:"Unsafe file declaration"});const key=`${f.owner}:${f.destinationPath.toLowerCase()}`;if(destinations.has(key))issues.push({code:"PKG_CONFLICT_FILE",path:f.destinationPath,message:"Duplicate destination"});destinations.add(key);if(!/^[a-f0-9]{64}$/.test(f.sha256))issues.push({code:"PKG_HASH_FORMAT",path:f.sourcePath,message:"Invalid SHA-256"});}}
if(m.databaseChanges?.destructive!==false)issues.push({code:"PKG_DB_DESTRUCTIVE",message:"Destructive database changes are blocked"});return issues.length?{issues}:{manifest:m,issues};}
export function validateArchiveEntries(entries:ArchiveEntry[]):ValidationIssue[]{const issues:ValidationIssue[]=[];if(entries.length>5000)issues.push({code:"PKG_ARCHIVE_ENTRY_LIMIT",message:"Too many entries"});let total=0;const seen=new Set<string>();for(const e of entries){total+=e.uncompressedSize;const k=e.path.toLowerCase();if(seen.has(k))issues.push({code:"PKG_ARCHIVE_DUPLICATE",path:e.path,message:"Duplicate or case-colliding path"});seen.add(k);if(!safeRelativePath(e.path))issues.push({code:"PKG_ARCHIVE_PATH",path:e.path,message:"Unsafe archive path"});if(e.uncompressedSize>52_428_800)issues.push({code:"PKG_ARCHIVE_ENTRY_SIZE",path:e.path,message:"Entry too large"});if(e.compressedSize>0&&e.uncompressedSize/e.compressedSize>100)issues.push({code:"PKG_ARCHIVE_RATIO",path:e.path,message:"Suspicious compression ratio"});const unixType=(e.externalAttributes>>>16)&0o170000;if(unixType===0o120000)issues.push({code:"PKG_ARCHIVE_SYMLINK",path:e.path,message:"Symlinks are prohibited"});}if(total>524_288_000)issues.push({code:"PKG_ARCHIVE_EXPANDED_LIMIT",message:"Expanded archive too large"});return issues;}
