-- PHASE P3 plugin platform foundation
CREATE TYPE "PluginStatus" AS ENUM ('DISCOVERED','VALIDATED','INSTALLED','ACTIVE','INACTIVE','FAILED','ROLLBACK_REQUIRED','UNINSTALLED');
CREATE TYPE "PluginInstallationStatus" AS ENUM ('PLANNED','APPROVED','INSTALLING','SUCCEEDED','FAILED','ROLLED_BACK');
CREATE TABLE "Plugin" ("id" TEXT PRIMARY KEY,"pluginKey" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"description" TEXT,"vendorKey" TEXT NOT NULL,"currentVersion" TEXT,"status" "PluginStatus" NOT NULL DEFAULT 'DISCOVERED',"tenantScope" TEXT NOT NULL,"manifest" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PluginVersion" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"version" TEXT NOT NULL,"manifest" JSONB NOT NULL,"packageSha256" TEXT NOT NULL,"signatureKeyId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PluginVersion_pluginId_fkey" FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "PluginVersion_pluginId_version_key" ON "PluginVersion"("pluginId","version");
CREATE TABLE "PluginInstallation" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"pluginVersionId" TEXT NOT NULL,"status" "PluginInstallationStatus" NOT NULL DEFAULT 'PLANNED',"planFingerprint" TEXT NOT NULL UNIQUE,"plan" JSONB NOT NULL,"requestedBy" TEXT NOT NULL,"approvedBy" TEXT,"startedAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"errorCode" TEXT,"errorMessage" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE,FOREIGN KEY("pluginVersionId") REFERENCES "PluginVersion"("id"));
CREATE TABLE "PluginFile" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"owner" TEXT NOT NULL,"destinationPath" TEXT NOT NULL,"sourcePath" TEXT NOT NULL,"sha256" TEXT NOT NULL,"sizeBytes" INTEGER NOT NULL,"installedVersion" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "PluginFile_owner_destinationPath_key" ON "PluginFile"("owner","destinationPath");
CREATE TABLE "PluginDependency" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"dependencyPluginId" TEXT NOT NULL,"versionRange" TEXT NOT NULL,"optional" BOOLEAN NOT NULL DEFAULT false,"mustBeActive" BOOLEAN NOT NULL DEFAULT true,FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE,FOREIGN KEY("dependencyPluginId") REFERENCES "Plugin"("id"));
CREATE UNIQUE INDEX "PluginDependency_pluginId_dependencyPluginId_key" ON "PluginDependency"("pluginId","dependencyPluginId");
CREATE TABLE "PluginPermission" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"permissionCode" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE); CREATE UNIQUE INDEX "PluginPermission_permissionCode_key" ON "PluginPermission"("permissionCode"); CREATE UNIQUE INDEX "PluginPermission_pluginId_permissionCode_key" ON "PluginPermission"("pluginId","permissionCode");
CREATE TABLE "PluginSetting" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"settingKey" TEXT NOT NULL,"scope" TEXT NOT NULL,"schema" JSONB NOT NULL,"defaultValue" JSONB,FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE); CREATE UNIQUE INDEX "PluginSetting_settingKey_key" ON "PluginSetting"("settingKey"); CREATE UNIQUE INDEX "PluginSetting_pluginId_settingKey_key" ON "PluginSetting"("pluginId","settingKey");
CREATE TABLE "PluginTenantAccess" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT false,"configuration" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE); CREATE UNIQUE INDEX "PluginTenantAccess_pluginId_tenantId_key" ON "PluginTenantAccess"("pluginId","tenantId");
CREATE TABLE "PluginMigration" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"version" TEXT NOT NULL,"operationId" TEXT NOT NULL,"operationType" TEXT NOT NULL,"status" TEXT NOT NULL,"plan" JSONB NOT NULL,"appliedAt" TIMESTAMP(3),"rolledBackAt" TIMESTAMP(3),FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE); CREATE UNIQUE INDEX "PluginMigration_pluginId_version_operationId_key" ON "PluginMigration"("pluginId","version","operationId");
CREATE TABLE "PluginBackup" ("id" TEXT PRIMARY KEY,"installationId" TEXT NOT NULL,"backupPath" TEXT NOT NULL,"sha256" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY("installationId") REFERENCES "PluginInstallation"("id") ON DELETE CASCADE);
CREATE TABLE "PluginRollback" ("id" TEXT PRIMARY KEY,"installationId" TEXT NOT NULL,"reason" TEXT NOT NULL,"requestedBy" TEXT NOT NULL,"status" TEXT NOT NULL,"details" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),FOREIGN KEY("installationId") REFERENCES "PluginInstallation"("id") ON DELETE CASCADE);
CREATE TABLE "PluginAuditEvent" ("id" TEXT PRIMARY KEY,"pluginId" TEXT,"actorId" TEXT,"action" TEXT NOT NULL,"outcome" TEXT NOT NULL,"reason" TEXT,"metadata" JSONB,"ipAddress" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE SET NULL);
CREATE TABLE "PluginHealthCheck" ("id" TEXT PRIMARY KEY,"pluginId" TEXT NOT NULL,"checkKey" TEXT NOT NULL,"type" TEXT NOT NULL,"target" TEXT,"required" BOOLEAN NOT NULL DEFAULT true,"lastStatus" TEXT,"lastMessage" TEXT,"checkedAt" TIMESTAMP(3),FOREIGN KEY("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE); CREATE UNIQUE INDEX "PluginHealthCheck_pluginId_checkKey_key" ON "PluginHealthCheck"("pluginId","checkKey");
