-- CreateTable
CREATE TABLE "Analytics" (
    "id" TEXT NOT NULL,
    "heroViews" INTEGER NOT NULL DEFAULT 0,
    "heroClicks" INTEGER NOT NULL DEFAULT 0,
    "ctr" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Analytics_pkey" PRIMARY KEY ("id")
);
